<?php

namespace ContainerWP2UnXb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCollaboratorControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CollaboratorController' shared autowired service.
     *
     * @return \App\Controller\CollaboratorController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CollaboratorController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/CollaboratorService.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/password-hasher/Hasher/UserPasswordHasherInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/password-hasher/Hasher/UserPasswordHasher.php';

        $container->services['App\\Controller\\CollaboratorController'] = $instance = new \App\Controller\CollaboratorController(new \App\Service\CollaboratorService(($container->privates['App\\Repository\\CollaboratorRepository'] ?? $container->load('getCollaboratorRepositoryService'))), new \Symfony\Component\PasswordHasher\Hasher\UserPasswordHasher(($container->privates['security.password_hasher_factory'] ?? $container->load('getSecurity_PasswordHasherFactoryService'))));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\CollaboratorController', $container));

        return $instance;
    }
}
