<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTJpuSnX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTJpuSnX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTJpuSnX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTJpuSnX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTJpuSnX\App_KernelDevDebugContainer([
    'container.build_hash' => 'TJpuSnX',
    'container.build_id' => '0b13b5c1',
    'container.build_time' => 1747819594,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTJpuSnX');
