<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCg24xcj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCg24xcj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCg24xcj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCg24xcj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCg24xcj\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cg24xcj',
    'container.build_id' => '5f332e89',
    'container.build_time' => 1747996038,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCg24xcj');
