<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_all_collaborator' => [[], ['_controller' => 'App\\Controller\\CollaboratorController::allCollaborator'], [], [['text', '/all/collaborators']], [], [], []],
    'app_collaborator_id' => [[], ['_controller' => 'App\\Controller\\CollaboratorController::collaboratorById'], [], [['text', '/collaborator/id']], [], [], []],
    'app_collaborator_email' => [[], ['_controller' => 'App\\Controller\\CollaboratorController::collaboratorByEmail'], [], [['text', '/collaborator/email']], [], [], []],
    'app_collaborator_random' => [[], ['_controller' => 'App\\Controller\\CollaboratorController::randomCollaborator'], [], [['text', '/collaborator/random']], [], [], []],
    'app_collaborator_by_category' => [[], ['_controller' => 'App\\Controller\\CollaboratorController::collaboratorsByCategory'], [], [['text', '/collaborators/category']], [], [], []],
    'app_collaborator_by_name' => [[], ['_controller' => 'App\\Controller\\CollaboratorController::collaboratorsByName'], [], [['text', '/collaborators/name']], [], [], []],
    'app_collaborator_by_text' => [[], ['_controller' => 'App\\Controller\\CollaboratorController::collaboratorsByText'], [], [['text', '/collaborators/filter']], [], [], []],
    'app_collaborator_create' => [[], ['_controller' => 'App\\Controller\\CollaboratorController::createCollaborator'], [], [['text', '/collaborator']], [], [], []],
    'app_collaborator_update' => [['id'], ['_controller' => 'App\\Controller\\CollaboratorController::updateCollaborator'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/collaborator']], [], [], []],
    'app_collaborator_delete' => [['id'], ['_controller' => 'App\\Controller\\CollaboratorController::deleteCollaborator'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/collaborator']], [], [], []],
    'App\Controller\CollaboratorController::allCollaborator' => [[], ['_controller' => 'App\\Controller\\CollaboratorController::allCollaborator'], [], [['text', '/all/collaborators']], [], [], []],
    'App\Controller\CollaboratorController::collaboratorById' => [[], ['_controller' => 'App\\Controller\\CollaboratorController::collaboratorById'], [], [['text', '/collaborator/id']], [], [], []],
    'App\Controller\CollaboratorController::collaboratorByEmail' => [[], ['_controller' => 'App\\Controller\\CollaboratorController::collaboratorByEmail'], [], [['text', '/collaborator/email']], [], [], []],
    'App\Controller\CollaboratorController::randomCollaborator' => [[], ['_controller' => 'App\\Controller\\CollaboratorController::randomCollaborator'], [], [['text', '/collaborator/random']], [], [], []],
    'App\Controller\CollaboratorController::collaboratorsByCategory' => [[], ['_controller' => 'App\\Controller\\CollaboratorController::collaboratorsByCategory'], [], [['text', '/collaborators/category']], [], [], []],
    'App\Controller\CollaboratorController::collaboratorsByName' => [[], ['_controller' => 'App\\Controller\\CollaboratorController::collaboratorsByName'], [], [['text', '/collaborators/name']], [], [], []],
    'App\Controller\CollaboratorController::collaboratorsByText' => [[], ['_controller' => 'App\\Controller\\CollaboratorController::collaboratorsByText'], [], [['text', '/collaborators/filter']], [], [], []],
    'App\Controller\CollaboratorController::createCollaborator' => [[], ['_controller' => 'App\\Controller\\CollaboratorController::createCollaborator'], [], [['text', '/collaborator']], [], [], []],
    'App\Controller\CollaboratorController::updateCollaborator' => [['id'], ['_controller' => 'App\\Controller\\CollaboratorController::updateCollaborator'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/collaborator']], [], [], []],
    'App\Controller\CollaboratorController::deleteCollaborator' => [['id'], ['_controller' => 'App\\Controller\\CollaboratorController::deleteCollaborator'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/collaborator']], [], [], []],
];
